### ISSUE TITLE
Pas d'icone dans l'écran d'application Gnome ou les favoris Gnome (Ubuntu, .deb)

### ISSUE THREAD

**Issue by adelcasse** [ringover/ringover-desktop-v2#5]
Sous Ubuntu 21.04, Gnome 3.38.5

Installation de l'application avec le fichier .deb fourni.

L'icone ne s'affiche pas dans la recherche d'applications (l'icone s'affichait avec une installation avec SNAP même si l'application elle-même ne se lançait pas cf. https://github.com/ringover/ringover-desktop-v2/issues/4 ) et dans les favoris

L'application se lance bien néanmoins.

![Screenshot from 2021-09-07 15-08-41](https://user-images.githubusercontent.com/403029/132350938-b650fa5d-3ecb-4d6e-946f-49012a1870a9.png)

![image](https://user-images.githubusercontent.com/403029/132351021-6a0ed712-53ce-4a1e-ac58-b4dc78e12cc7.png)

**Comment by koussaimb** [comment]
Bonjour 

Vous pouvez utiliser la version via le store du linux, le probleme fixé dans cette version 

https://snapcraft.io/ringover

Merci d'installer cette module avant 

https://snapcraft.io/ringover

Merci
